### ISSUE TITLE
Attribute data-vis-set is set twice on 2 different widgets

### ISSUE THREAD

**Issue by DeepCoreSystem** [ioBroker/ioBroker.vis-jqui-mfd#1]
The attribute 'data-vis-set' is set twice on 2 different widgets:

![2016-07-20 16_51_12-http___192 168 1 121_8082_vis_index html overview](https://cloud.githubusercontent.com/assets/3703938/16991046/948645ce-4e9a-11e6-9498-ee9ec8476517.png)
![2016-07-20 16_52_13-http___192 168 1 121_8082_vis_index html overview](https://cloud.githubusercontent.com/assets/3703938/16991045/94860db6-4e9a-11e6-8116-969123a1e186.png)

**Comment by GermanBluefox** [comment]
Fixed. Please verify
