### ISSUE TITLE
'Light/Dimmer' und 'Custom10' : Kein Icon bei Wert '0' when 'Icon Color' gesetzt ist.

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.vis-jqui-mfd#10]
Repro siehe https://forum.iobroker.net/viewtopic.php?f=30&t=14983
Das Icon für Wert '0' wird an die falsche Position gezeichnet, wie beim Test mit Custom10 zu sehen ist.

**Comment by GermanBluefox** [comment]
Sieht so aus, als ob hier https://github.com/ioBroker/ioBroker.vis-jqui-mfd/blob/master/widgets/jqui-mfd.html#L1548 was falsch ist.

**Comment by GermanBluefox** [comment]
Please test 1.0.12

**Comment by Breisgauer** [comment]
Sieht gut aus, mein Repro zeigt keinen Fehler mehr!
