### ISSUE TITLE
VIS jqui - log: type "boolean" but received type "number"

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.vis-jqui-mfd#26]
vgl.:
https://forum.iobroker.net/topic/54188/vis-jqui-log-type-boolean-but-received-type-number?_=1649927342788

jqui erzeugt warn-Meldungen im log.

**Comment by Apollon77** [comment]
You can set min as true and max as false (or other way around) then on will be the one logical value and off the other

**Comment by bahnuhr** [comment]
Hallo Ingo,
und genau diese Einstellung gibt es bei diesem Widget nicht !

mfg
Dieter

**Comment by Apollon77** [comment]
@bahnuhr Das Widget jkommt dirkt aus vsi ... und ja schreibt 0/1 rein :-( legst das Issue bei vis bitte nochmal an? Ggff kann BF ds dann beim vis rework mit berücksichtigen

**Comment by Apollon77** [comment]
PS: Freche variante aktuellwäre ein Alias der konvertierung macht? ;-)
