### ISSUE TITLE
Frage:  Version 1.1.0 nicht freigegeben / nicht installierbar

### ISSUE THREAD

**Issue by PiemurIsBack** [ioBroker/ioBroker.vis-jqui-mfd#34]
Hallo 
ich bin froh zu sehen, dass die Version 1.1 mit Vis-2 funktionieren soll.

Leider wird die Version (noch) nicht im Adapter (Stable) zum Update angeboten.
![image](https://github.com/ioBroker/ioBroker.vis-jqui-mfd/assets/116312454/c4171140-0350-4791-aee3-e1fe8ed10350)

Wann erfolgt die Freigabe?
muss dies über NPM installiert werden?

**Comment by zaphod2** [comment]
Würde mich auch interessieren. Bekomme in Vis-2 nicht alles angezeigt.
Danke für die Mühen.

**Comment by mcm1957** [comment]
@GermanBluefox 
@Apollon77 

Es gibt hier ein Versionierungsproblem. Siehe failing tests. Bitte mal ansehen.
https://github.com/ioBroker/ioBroker.vis-jqui-mfd/actions/runs/7126815944/job/19405473608

**Comment by mcm1957** [comment]
should be fixed with 1.1.1
@Apollon77 please consider closing
